POST http://localhost:7899/user
Content-Type: application/json

{
    "username":"dika",
    "email":"dikagege@gmail.com",
    "firstName":"dika",
    "lastName":"syauqi",
    "password":"123",
    "address":"padang",
    "phoneNumber":"1"
}

###
GET http://localhost:7899/user

###
POST http://localhost:7899/user/login
Content-Type: application/json

{
     "username":"dika",
    "password":"322"
}

###
DELETE http://localhost:7899/user/logout

###
PUT http://localhost:7899/user/7
Content-Type: application/json

{            
      "address":"jawa 3"
}

###
DELETE http://localhost:7899/user/8

###
PUT http://localhost:7899/user/changePassword/9
Content-Type: application/json

{
     "oldPassword":"123",
     "newPassword":"322"
}

###
GET http://localhost:7899/user/72
