POST http://localhost:7899/user
Content-Type: application/json

{
    "username":"farhanSyauqi",
    "email":"farhansyauqi@gmail.com",
    "password":"123",
    "address":"padang",
    "phoneNumber":"1"
}

###
GET http://localhost:7899/user

###
POST http://localhost:7899/user/login
Content-Type: application/json

{
     "username":"farhan",
    "password":"123"
}

###
DELETE http://localhost:7899/user/logout

###
PUT http://localhost:7899/user/3
Content-Type: application/json

{        
      "address":"jawa 3"
}

###
DELETE http://localhost:7899/user/2