POST http://localhost:7899/api/user
Content-Type: application/json

{
    "username":"dika",
    "email":"dikagege@gmail.com",
    "firstName":"dika",
    "lastName":"syauqi",
    "password":"123",
    "address":"padang",
    "phoneNumber":"1",
    "jenisKelamin":"laki-laki"
}

###
GET http://localhost:7899/api/user

###
POST http://localhost:7899/api/login
Content-Type: application/json

{
     "username":"dika",
    "password":"322"
}

###
DELETE http://localhost:7899/api/logout

###
PUT http://localhost:7899/user/7
Content-Type: application/json

{            
      "address":"jawa 3"
}

###
DELETE http://localhost:7899/api/user/6

###
PUT http://localhost:7899/user/changePassword/9
Content-Type: application/json

{
     "oldPassword":"123",
     "newPassword":"322"
}

###
GET http://localhost:7899/user/72


###
POST http://localhost:7899/history
Content-Type: application/json

{
     "idUser": 23,
      "score": 60,
      "gold": 80,
      "winLose": true,
      "exp": 80
}

###
DELETE http://localhost:7899/dashboard/history/delete/20
Content-Type: application/json

{
     "id":5
}

